<?php

namespace CodeGreenCreative\Aweber\Aweber\Exceptions;

/**
 * AWeberOAuthException
 *
 * OAuth exception, as generated by an API JSON error response
 * @uses AWeberException
 * @package
 * @version $id$
 */
class AweberOauthException extends AweberException
{
    public function __construct($type, $message)
    {
        $this->type = $type;
        $this->message = $message;
        parent::__construct("{$type}: {$message}");
    }
}
